#!/bin/bash

arch -arm64 brew install rename
arch -arm64 brew install protobuf@3
arch -arm64 brew link --overwrite protobuf@3

npm i --location=global grpc-tools@^1.11.2 --unsafe-perm
npm i --location=global grpc_tools_node_protoc_ts@^5.3.3 --unsafe-perm
npm i --location=global typescript --unsafe-perm
npm i --location=global @bufbuild/buf --unsafe-perm
npm i --location=global google-protobuf --unsafe-perm
npm i --unsafe-perm
npm install
